### ISSUE TITLE
Python3 compatibility

### ISSUE THREAD

**Issue by getzze** [getzze/Watcher#3]
Check with python3 and python2

**Comment by szepeviktor** [comment]
Works for both 2 and 3

``` python
try:
    return isinstance(obj, basestring)
except NameError:
    return isinstance(obj, str)
```

**Comment by szepeviktor** [comment]
https://github.com/getzze/Watcher/blob/master/watcher.py#L67-L69
`open()` should be **b**inary.

**Comment by szepeviktor** [comment]
`import lockfile.pidlockfile` then `lockfile.pidlockfile.AlreadyLocked` and `lockfile.pidlockfile.PIDLockFile(path)`
https://github.com/openstack/pylockfile

**Comment by szepeviktor** [comment]
Typo: `gid and uid **tu** run the daemon.`

**Comment by getzze** [comment]
What is the problem of opening the files for stdin, stdout and stderr not in binary?
Normally the `daemon` module supports non-binary files, see https://pypi.python.org/pypi/python-daemon/ and  https://www.python.org/dev/peps/pep-3143/#daemoncontext-objects

Also, can you make pull request instead of comments? It is easier to comment the changes then and to accept them.
Thanks

**Comment by szepeviktor** [comment]
I've added binary `open()`-s because python 3.4 told me:

```
Traceback (most recent call last):
  File "watcher.py", line 500, in <module>
    daemon = DaemonRunner(watcher, **options)
  File "watcher.py", line 69, in __init__
    self.daemon_context.stderr = open(stderr or '/dev/null', 'w+', buffering=0)
ValueError: can't have unbuffered text I/O
```

Then I've googled.

**Comment by szepeviktor** [comment]
I cannot fork your repo because I end up in splitbrain's one.
https://github.com/szepeviktor/Watcher/commit/23a1e006cbe0ac8a038a135ee6e02397fe6d8547
In a patch:
https://github.com/szepeviktor/Watcher/commit/23a1e006cbe0ac8a038a135ee6e02397fe6d8547.patch

**Comment by getzze** [comment]
Did you try `git clone https://github.com/getzze/Watcher` ?
Indeed, in python 3, unbuffered files can only be used in binary mode. I suspect this will lead to encoding errors, but the redirection of stdin, stdout and stderr is not implemented in watcher anyway.

**Comment by szepeviktor** [comment]
Cloning works but I cannot fork two repos being forks of each other.

**Comment by szepeviktor** [comment]
Please make those changes for `lockfile`, it had API changes.

**Comment by szepeviktor** [comment]
I think stdin and sdtout also need to have **b**.
